### ISSUE TITLE
Color combinations don't communicate default ordering

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/graphics-styleguide#6]
The graphics style guide offers no guidance on the default or suggested ordering of colors for data visualizations. It would be great if the palette with eight colors reflected the default order for adding colors. 

![colors1](https://user-images.githubusercontent.com/11818850/39834600-837a068c-539b-11e8-9edb-cf12086842e5.png)

The subsequent groupings should then reflect the order from above. 

![color2](https://user-images.githubusercontent.com/11818850/39834604-85e4c9e8-539b-11e8-87eb-9a73d0f2bedc.png)

![color3](https://user-images.githubusercontent.com/11818850/39834612-890c8980-539b-11e8-98d2-4a27892419fe.png)

![color4](https://user-images.githubusercontent.com/11818850/39834614-8a75e08c-539b-11e8-87fd-949a7201c2d0.png)

`library(urbnthemes)` adds colors in this order: `#1696d2`, `#fdbf11`, `#000000`, `#d2d2d2`, `#ec008b`, `#55b748`, `#5c5859`, `#db2b27`

**Comment by alicefeng** [comment]
Per @bchartoff 's recommendation, the order for categorical colors should be:

 "#1696d2", "#fdbf11", "#000000", "#d2d2d2", "#ec008b", "#55b748", "#5c5859", "#db2b27”
(Cyan, yellow, black, grey, magenta, green, space grey, red)

**Comment by alicefeng** [comment]
Addressed in #21
